name: Lint code

on: [push]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                ref: ${{ github.head_ref }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                extensions: ACTIONS.PHP.EXTENSIONS
                tools: composer:v2
                coverage: xdebug

            - name: Install PHP dependencies
              run: composer update --no-interaction --no-progress

            - name: Run Linter
              run: composer run lint

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: 'chore: fix styling'
