name: Run Tests

on: [ACTIONS.EVENTS]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ACTIONS.OS]
        php: [ACTIONS.PHP.VERSIONS]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: ACTIONS.PHP.EXTENSIONS
        tools: composer:v2
        coverage: xdebug

    - name: Install PHP dependencies
      run: composer update --no-interaction --no-progress

    - name: Run Tests
      run: composer run test
